#!/bin/bash
### BEGIN INIT INFO
# Provides:          #INSTANCE_NAME#
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start #INSTANCE_NAME#
# Description:       Start tomcat instance #INSTANCE_NAME#
### END INIT INFO

set -e

[[ 0 -ne $EUID ]] && echo "requires root access" && exit 1

INSTANCE_PATH="#INSTANCE_PATH#"
export JAVA_HOME="#JAVA_HOME#"

[ -d "$INSTANCE_PATH" ] && echo "setup error : missing or not-accessible instance path" && exit 1
case $0 in
   start )
      "$INSTANCE_PATH/bin/startup.sh"
      ;;
   stop )
      "$INSTANCE_PATH/bin/shutdown.sh"
      ;;
   * ) echo "expected command : start|stop"
      ;;
esac
